/* Generated By:JJTree&JavaCC: Do not edit this line. SimpleCalculatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleCalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int DIGITS = 3;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int DIVIDE = 7;
  /** RegularExpression Id. */
  int TIMES = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int PREVIOUS = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "<DIGITS>",
    "\"+\"",
    "<NUMBER>",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"$\"",
  };

}
