/* Generated By:JavaCC: Do not edit this line. SimpleCalculatorTreeConstants.java Version 5.0 */
public interface SimpleCalculatorTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTTERM = 1;
  public int JJTEXPRESSION = 2;
  public int JJTPRIMARY = 3;


  public String[] jjtNodeName = {
    "PROGRAM",
    "TERM",
    "EXPRESSION",
    "PRIMARY",
  };
}
/* JavaCC - OriginalChecksum=df56484d2bc53a4348de1bc999319beb (do not edit this line) */
